---
# You can override vars by using host or group vars

cephx: true


##########
# DOCKER #
##########

ceph_containerized_deployment: false
ceph_mds_docker_username: ceph
ceph_mds_docker_imagename: daemon
