---

- name: stop auth-proxy container
  service: name=auth-proxy state=stopped

- name: cleanup iptables for auth proxy
  shell: iptables -D INPUT -p tcp --dport {{ item }} -j ACCEPT -m comment --comment "{{ auth_proxy_rule_comment }} ({{ item }})"
  become: true
  with_items:
    - "{{ auth_proxy_port }}"
