---
- name: create red hat storage package directory
  file: >
    path={{ ceph_stable_rh_storage_mount_path }}
    state=directory

- name: get red hat storage packages
  get_url: >
    url={{ ceph_stable_rh_storage_url }}
    dest={{ ceph_stable_rh_storage_download_path }}/rh-storage.iso
    sha256sum={{ ceph_stable_rh_storage_iso_checksum }}

- name: mount red hat storage iso file
  mount: >
    name={{ ceph_stable_rh_storage_mount_path }}
    src={{ ceph_stable_rh_storage_download_path }}/rh-storage.iso
    fstype=iso9660
    state=mounted
