- hosts: all
  sudo: true
  tasks:
    - yum: "name=https://repos.fedorapeople.org/repos/openstack/openstack-kilo/rdo-release-kilo-1.noarch.rpm"
      when: ansible_os_family == "RedHat"
    - apt: "update_cache=yes name={{ item }}"
      with_items:
        - unzip
        - vim-nox
        - curl
        - python-software-properties
        - git 
        - mercurial
        - build-essential
        - perl
        - librbd-dev
      when: ansible_os_family == "Debian"
    - yum: "update_cache=yes name={{ item }}"
      with_items:
        - ntp
        - unzip
        - vim
        - curl
        - git
        - mercurial
        - openvswitch
        - gcc
        - perl
        - librbd1-devel
      when: ansible_os_family == "RedHat"
    - shell: systemctl enable ntpd
      when: ansible_os_family == "RedHat"
    - shell: creates=/usr/local/go/bin/go curl -L https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz | tar -xvz -C /usr/local
    - get_url: 
        url: https://github.com/coreos/etcd/releases/download/v2.1.1/etcd-v2.1.1-linux-amd64.tar.gz
        dest: /tmp/etcd.tar.gz
    - shell: creates=/usr/bin/etcd tar vxzf /tmp/etcd.tar.gz && mv etcd-v2.1.1-linux-amd64/etcd* /usr/bin
    - copy:
        dest: /etc/profile.d/00golang.sh
        content: "export PATH=/opt/golang/bin:/usr/local/go/bin:$PATH\nexport GOPATH=/opt/golang"
    - shell: creates=/usr/bin/docker curl https://experimental.docker.com | bash
    - lineinfile:
        create: yes
        dest: /etc/default/docker
        line: ". /etc/profile.d/00golang.sh && . /etc/profile.d/envvar.sh"
    - user: name=vagrant groups=docker append=yes
    - get_url:
        dest: "{{ item.dest }}"
        url: "{{ item.url }}"
      with_items:
        - { 
            url: "https://cisco.box.com/shared/static/v1dvgoboo5zgqrtn6tu27vxeqtdo2bdl.deb",
            dest: /tmp/ovs-common.deb
          }
        - { 
            url: "https://cisco.box.com/shared/static/ymbuwvt2qprs4tquextw75b82hyaxwon.deb",
            dest: /tmp/ovs-switch.deb
          }
      when: ansible_os_family == "Debian"
    - apt: "deb=/tmp/ovs-common.deb"
      when: ansible_os_family == "Debian"
    - apt: "deb=/tmp/ovs-switch.deb"
      when: ansible_os_family == "Debian"
    - service: "name=openvswitch enabled=yes state=started"
      when: ansible_os_family == "RedHat"
    - shell: "ovs-vsctl set-manager {{ item }}"
      with_items:
        - "tcp:127.0.0.1:6640"
        - "ptcp:6640"
    - get_url: 
        url: https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
        dest: /tmp/consul.zip
    - shell: "chdir=/tmp creates=/usr/bin/consul unzip /tmp/consul.zip && mv /tmp/consul /usr/bin"
    # - copy: src=files/{{ item }} dest=/etc/default/{{ item }}
    #   with_items:
    #     - consul
    #     - etcd
    #     - netplugin
    #     - netmaster
    # - copy: src=files/{{ item }}.service dest=/etc/systemd/system/{{ item }}.service
    #   with_items:
    #     - volmaster 
    #     - volplugin
    #     - netmaster
    #     - netplugin
    #     - etcd
    #     - consul
    # - shell: systemctl daemon-reload
