---
- name: make sure journal_size configured
  fail: msg="journal_size must be configured. See http://ceph.com/docs/master/rados/configuration/osd-config-ref/"
  when: journal_size|int == 0

- name: make sure monitor_interface configured
  fail: msg="monitor_interface must be configured. Interface for the monitor to listen on"
  when: monitor_interface == 'interface'

- name: make sure cluster_network configured
  fail: msg="cluster_network must be configured. Ceph replication network"
  when: cluster_network == '0.0.0.0/0'

- name: make sure public_network configured
  fail: msg="public_network must be configured. Ceph public network"
  when: public_network == '0.0.0.0/0'
