---
- name: install dependencies
  apt: >
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - python-pycurl
    - ntp
    - hdparm

- name: install the Ceph repository stable key
  apt_key: >
    data="{{ lookup('file', 'cephstable.asc') }}"
    state=present
  when: ceph_stable

- name: install the Ceph development repository key
  apt_key: >
    data="{{ lookup('file', 'cephdev.asc') }}"
    state=present
  when: ceph_dev

- name: install Intank Ceph Enterprise repository key
  apt_key: >
    data="{{ lookup('file', 'cephstableice.asc') }}"
    state=present
  when: ceph_stable_ice

- name: add Ceph stable repository
  apt_repository: >
    repo="deb http://ceph.com/debian-{{ ceph_stable_release }}/ {{ ansible_lsb.codename }} main"
    state=present
  changed_when: false
  when: ceph_stable

- name: add Ceph development repository
  apt_repository: >
    repo="deb http://gitbuilder.ceph.com/ceph-deb-{{ ansible_lsb.codename }}-x86_64-basic/ref/{{ ceph_dev_branch }} {{ ansible_lsb.codename }} main"
    state=present
  changed_when: false
  when: ceph_dev

- name: add Inktank Ceph Enterprise repository
  apt_repository: >
    repo="deb file://{{ ceph_stable_ice_temp_path }} {{ ansible_lsb.codename }} main"
    state=present
  changed_when: false
  when: ceph_stable_ice

- name: install Ceph
  apt: >
    pkg={{ item }}
    state=latest
  with_items:
    - ceph
    - ceph-common    #|
    - ceph-fs-common #|--> yes, they are already all dependencies from 'ceph'
    - ceph-fuse      #|--> however while proceding to rolling upgrades and the 'ceph' package upgrade
    - ceph-mds       #|--> they don't get update so we need to force them
    - libcephfs1     #|

- name: configure rbd clients directories
  file: >
    path={{ item }}
    state=directory
    owner=libvirt-qemu
    group=kvm
    mode=0755
  with_items:
   - rbd_client_log_path
   - rbd_client_admin_socket_path
  when: rbd_client_directories
