---
# This role contains tasks for configuring and starting netmaster and netplugin service

- name: download netmaster and netplugin
  get_url:
    validate_certs: no
    url: https://github.com/contiv/netplugin/releases/download/v0.0.0-11-07-2015.02-43-45.UTC/netplugin-v0.0.0-11-07-2015.02-43-45.UTC.tar.bz2
    dest: /tmp/contivnet.tar.bz2

- name: install netmaster and netplugin
  shell: tar vxjf /tmp/contivnet.tar.bz2
  args:
    chdir: /usr/bin/
    creates: netmaster

- name: copy environment file for netmaster
  copy: src=netmaster dest=/etc/default/netmaster
  when: run_as == "master"

- name: copy systemd units for netmaster
  copy: src=netmaster.service dest=/etc/systemd/system/netmaster.service
  when: run_as == "master"

- name: start netmaster
  shell: systemctl daemon-reload && systemctl start netmaster
  when: run_as == "master"

- name: copy environment file for netplugin
  copy: src=netplugin dest=/etc/default/netplugin

- name: copy systemd units for netplugin
  copy: src=netplugin.service dest=/etc/systemd/system/netplugin.service

- name: start netplugin
  shell: systemctl daemon-reload && systemctl start netplugin

- name: setup netmaster host alias on master
  shell: echo "{{ node_addr }} netmaster" >> /etc/hosts
  when: run_as == "master"

- name: setup netmaster host alias on workers
  shell: echo "{{ online_master_addr }} netmaster" >> /etc/hosts
  when: run_as == "worker"
