---

- include: pre_requisite.yml
  when: not ceph_containerized_deployment

- include: journal_collocation.yml
  when: journal_collocation and not ceph_containerized_deployment

- include: raw_multi_journal.yml
  when: raw_multi_journal and not ceph_containerized_deployment

- include: osd_directory.yml
  when: osd_directory and not ceph_containerized_deployment

- include: docker.yml
  when: ceph_containerized_deployment
