---
# NOTE (leseb): some devices might miss partition label which which will result
# in ceph-disk failing to prepare OSD. Thus zapping them prior to prepare the OSD
# ensures that the device will get successfully prepared.
- name: erasing partitions and labels from OSD disk(s)
  command: ceph-disk zap {{ item }}
  with_items: devices
  changed_when: false
  when:
    zap_devices and
    (journal_collocation or raw_multi_journal)

- name: erasing partitions and labels from the journal device(s)
  command: ceph-disk zap {{ item }}
  with_items: raw_journal_devices
  changed_when: false
  when:
    zap_devices and
    raw_multi_journal
