---
- include: pre_requisite.yml
  when: not ceph_containerized_deployment

- include: install_redhat.yml
  when:
    ansible_os_family == 'RedHat' and
    radosgw_frontend == 'apache' and not
    ceph_containerized_deployment

- include: install_debian.yml
  when:
    ansible_os_family == 'Debian' and
    radosgw_frontend == 'apache' and not
    ceph_containerized_deployment

- name: install Rados Gateway
  apt: >
    pkg=radosgw
    state=present
    update_cache=yes
  when:
    ansible_os_family == 'Debian' and not
    ceph_containerized_deployment

- name: install Rados Gateway
  yum: >
    name=ceph-radosgw
    state=present
  when:
    ansible_os_family == 'RedHat' and not
    ceph_containerized_deployment

- include: openstack-keystone.yml
  when: radosgw_keystone

- include: start_radosgw.yml
  when: not ceph_containerized_deployment

- include: docker.yml
  when: ceph_containerized_deployment
