---
# This playbook deploys the configuration based on special purpose host-groups.

# devtest hosts correspond to the dev, lab and vagrant based machines for contiv projects.
# Here we will install the base packages needed for those environments.
# XXX: this is used by the 'contiv/build' project right now. But hopefully soon
# we can use it as replacement for 'contiv/lab' with some more refinements.
- hosts: devtest
  sudo: true
  environment: env
  roles:
  - { role: base }
  - { role: serf }
  - { role: docker }

# cluster-control hosts corresponds to the first machine in the cluster that is provisioned
# to bootstrap the cluster by starting cluster manager and inventory database (collins)
- hosts: cluster-control
  sudo: true
  environment: env
  roles:
  - { role: docker }
  - { role: contiv_cluster }

- hosts: ceph-hosts
  sudo: true
  environment: env
  roles:
  - { role: ceph-mon, mon_group_name: ceph-hosts }
  - { role: ceph-osd, osd_group_name: ceph-hosts }

# service-master hosts correspond to cluster machines that run the master/controller
# logic of the infra services
- hosts: service-master
  sudo: true
  environment: env
  roles:
  - { role: docker }
  - { role: etcd }
  - { role: swarm, run_as: master }
  - { role: contiv_network, run_as: master }
  - { role: contiv_storage, run_as: master }

# service-worker hosts correspond to cluster machines that run the worker/driver
# logic of the infra services.
- hosts: service-worker
  sudo: true
  environment: env
  roles:
  - { role: docker }
  - { role: etcd }
  - { role: swarm, run_as: worker }
  - { role: contiv_network, run_as: worker }
  - { role: contiv_storage, run_as: worker }
